"""Built-in extractor module catalog for Lola UI/automation.

Adapters describe how evidence sources fit together. Ghidra is for native PE/ELF
static analysis when installed; Frida remains an explicitly authorized attach-only
runtime evidence source and is never required for ordinary extraction.
"""
MODULES=[
 {"id":"workflow","mode":"static-flow","purpose":"Map Python entry points, dependency edges, process launches and fallback flow."},
 {"id":"head","mode":"static-head","purpose":"Identify entry and dependency heads in the Python code graph."},
 {"id":"python","mode":"python-capability","purpose":"Python workbench capability: python."},
 {"id":"linux","mode":"python-capability","purpose":"Python workbench capability: linux."},
 {"id":"host","mode":"python-capability","purpose":"Python workbench capability: host."},
 {"id":"pyconverter","mode":"python-capability","purpose":"Python workbench capability: pyconverter."},
 {"id":"pyinverter","mode":"python-capability","purpose":"Python workbench capability: pyinverter."},
 {"id":"pyheader","mode":"python-capability","purpose":"Python workbench capability: pyheader."},
 {"id":"pytrace","mode":"python-capability","purpose":"Python workbench capability: pytrace."},
 {"id":"pylink","mode":"python-capability","purpose":"Python workbench capability: pylink."},
 {"id":"pyurls","mode":"python-capability","purpose":"Python workbench capability: pyurls."},
 {"id":"pydecorder","mode":"python-capability","purpose":"Python workbench capability: pydecorder."},
 {"id":"pyencorder","mode":"python-capability","purpose":"Python workbench capability: pyencorder."},
 {"id":"pylayer","mode":"python-capability","purpose":"Python workbench capability: pylayer."},
 {"id":"pylist","mode":"python-capability","purpose":"Python workbench capability: pylist."},
 {"id":"pyghidra","mode":"python-capability","purpose":"Python workbench capability: pyghidra."},
 {"id":"pyfrida","mode":"python-capability","purpose":"Python workbench capability: pyfrida."},
 {"id":"pynano","mode":"python-capability","purpose":"Python workbench capability: pynano."},
 {"id":"pyupdate","mode":"python-capability","purpose":"Python workbench capability: pyupdate."},
 {"id":"pyupgrade","mode":"python-capability","purpose":"Python workbench capability: pyupgrade."},
 {"id":"pypath","mode":"static-python-graph","purpose":"Map Python paths, imports, entry points and subprocess launch sites without importing target code."},
 {"id":"exfallback","mode":"bot-coordinator","purpose":"Continue unresolved EX4/EX5 diagnosis across available evidence bots and request optional evidence."},
 {"id":"exevidence","mode":"evidence-request","purpose":"Show useful optional evidence for an unresolved EX4/EX5 case."},
 {"id":"exproblem","mode":"evidence-router","purpose":"Diagnose EX4/EX5 problems from bounded artifact, source-reference and local log evidence."},
 {"id":"exaskmt5","mode":"evidence-router-ai","purpose":"Route EX4/EX5 evidence through the configured MT5 AI after local diagnosis."},
 {"id":"mt5ai","mode":"mcp-client","purpose":"Send bounded MQL/EX evidence questions to an explicitly configured MetaTrader 5 MCP AI tool."},
 {"id":"mt5mcp","mode":"mcp-discovery","purpose":"Discover authorized MetaTrader 5 MCP capabilities and tools."},
 {"id":"metatrader","mode":"specialist","purpose":"Built-in MT4/MT5 source specialist and capability report."},
 {"id":"mtcheck","mode":"static-source","purpose":"Check MQL4/MQL5 source structure and event handlers."},
 {"id":"mtcompile","mode":"compile","purpose":"Compile user-selected MQL4/MQL5 source with an installed MetaEditor."},
 {"id":"help","mode":"escalation","purpose":"Create a structured help request when a specialist bot cannot resolve a task."},
 {"id":"mergecode","mode":"integration-plan","purpose":"Plan provenance-preserving integration of compatible code components."},
 {"id":"combineidea","mode":"analysis","purpose":"Combine compatible architecture ideas without blindly concatenating code."},
 {"id":"codeidea","mode":"analysis","purpose":"Generate evidence-based code architecture improvement ideas."},
 {"id":"codeintelligent","mode":"analysis","purpose":"Identify target format and propose bounded inspection/integration routes."},
 {"id":"codewrap","mode":"integration-plan","purpose":"Create an auditable wrapper plan around inspection/extraction/conversion."},
 {"id":"codescriptidea","mode":"analysis","purpose":"Suggest script/workflow structure for a selected code target."},
 {"id":"codecompile","mode":"compile-plan","purpose":"Select a language-specific compile or syntax-check route."},
 {"id":"codeextract","mode":"static","purpose":"Select a safe static extraction route by code format."},
 {"id":"codeconvert","mode":"convert-plan","purpose":"Select a compatible representation conversion route."},
 {"id":"codeencrypt","mode":"crypto-plan","purpose":"Plan authenticated encryption for user-owned workspace artifacts."},
 {"id":"codedecrypt","mode":"crypto-plan","purpose":"Plan authorized decryption of user-owned workspace artifacts; no password guessing or protection bypass."},
 {"id":"codecheckall","mode":"analysis","purpose":"Repository-wide Python syntax and cross-function inspection."},
 {"id":"codetarget","mode":"analysis","purpose":"Focus inspection on a named code target."},
 {"id":"codeidentify","mode":"analysis","purpose":"Identify files and definitions matching a target."},
 {"id":"codemethode","mode":"analysis","purpose":"Inventory methods/functions by file or target."},
 {"id":"codeexpanding","mode":"analysis","purpose":"Show safe architecture expansion points."},
 {"id":"codeextra","mode":"analysis","purpose":"Show additional static code inspection opportunities."},
 {"id":"codecodecodelayer","mode":"analysis","purpose":"Map code into interface/dispatch/extract/convert/office/OCR/analysis/runtime layers."},
 {"id":"skeleton","mode":"analysis","purpose":"Build repository import and definition skeleton."},
 {"id":"troubleshooting","mode":"analysis","purpose":"Report static Python syntax problems."},
 {"id":"codesummary","mode":"analysis","purpose":"Summarize repository code structure."},
 {"id":"codecheck","mode":"analysis","purpose":"Static Python code check."},
 {"id":"pycheck","mode":"analysis","purpose":"Python syntax and cross-function check."},
 {"id":"pdfrichhtml","mode":"convert","purpose":"Render PDF pages to interactive HTML with searchable/OCR text."},
 {"id":"batchofficehtml","mode":"batch-convert","purpose":"Convert supported office-document folders to HTML."},
 {"id":"office2html","mode":"convert","purpose":"Convert office documents to responsive semantic HTML."},
 {"id":"pdf2html","mode":"reconstruct","purpose":"PDF pages and text to responsive HTML with page provenance."},
 {"id":"word2html","mode":"convert","purpose":"DOCX paragraphs and tables to semantic HTML."},
 {"id":"excel2html","mode":"convert","purpose":"XLSX worksheets and cells to responsive HTML tables."},
 {"id":"pdfocr","mode":"ocr","purpose":"Per-page PDF OCR with searchable/scanned detection and provenance."},
 {"id":"ocrreadiness","mode":"static","purpose":"Detect which PDF pages need OCR."},
 {"id":"searchablepdf","mode":"ocr-export","purpose":"Create a new searchable OCR PDF when OCRmyPDF is available."},
 {"id":"officeconvert","mode":"convert","purpose":"Execute local office document conversions using built-in adapters."},
 {"id":"officecapabilities","mode":"reference","purpose":"Report available document conversion backends."},
 {"id":"documentconvert","mode":"convert-plan","purpose":"PDF Word Excel and office-document conversion routing."},
 {"id":"pdf2word","mode":"reconstruct","purpose":"PDF to editable Word reconstruction."},
 {"id":"pdf2excel","mode":"reconstruct","purpose":"PDF table extraction to Excel."},
 {"id":"word2pdf","mode":"render","purpose":"Word-compatible document to PDF export."},
 {"id":"excel2pdf","mode":"render","purpose":"Spreadsheet to PDF export."},
 {"id":"word2excel","mode":"structured","purpose":"Word tables to Excel worksheets."},
 {"id":"excel2word","mode":"structured","purpose":"Excel worksheets to editable Word tables."},
 {"id":"py","mode":"static-source","purpose":"Python AST, imports, classes and function evidence."},
 {"id":"convertany","mode":"convert-plan","purpose":"Auto-detect compatible representation conversion path."},
 {"id":"anyformat","mode":"convert-plan","purpose":"Wildcard format conversion/evidence fallback."},
 {"id":"dex2smali","mode":"convert","purpose":"DEX to Smali representation."},
 {"id":"smali2dex","mode":"convert","purpose":"Smali to DEX representation."},
 {"id":"dex2java","mode":"reconstruct","purpose":"DEX to reconstructed Java source."},
 {"id":"smali2java","mode":"reconstruct","purpose":"Smali to reconstructed Java source."},
 {"id":"androidconvert","mode":"reference","purpose":"Android format conversion matrix."},
 {"id":"dex","mode":"static","purpose":"DEX header/table evidence."},
 {"id":"class","mode":"static","purpose":"Java class header/constant-pool evidence."},
 {"id":"jar","mode":"static","purpose":"JAR package inventory."},
 {"id":"apk","mode":"static","purpose":"APK package inventory."},
 {"id":"aab","mode":"static","purpose":"Android App Bundle inventory."},
 {"id":"wasm","mode":"static","purpose":"WebAssembly header evidence."},
 {"id":"sqlite","mode":"static","purpose":"SQLite read-only schema inventory."},
 {"id":"json","mode":"static","purpose":"JSON structural inventory."},
 {"id":"protobuf","mode":"static","purpose":"Schema-less protobuf wire inventory."},
 {"id":"pak","mode":"static","purpose":"PAK raw-container evidence."},
 {"id":"img","mode":"static","purpose":"IMG raw-container evidence."},
 {"id":"iso","mode":"static","purpose":"ISO raw-container evidence."},
 {"id":"exe","mode":"static-native","purpose":"PE/EXE header and section evidence; target is never loaded."},
 {"id":"so","mode":"static-native","purpose":"ELF/shared-object header and section evidence; target is never loaded."},
 {"id":"dat","mode":"static","purpose":"Generic DAT/raw classification by content, signatures, chunks and strings."},
 {"id":"codecli","mode":"interface","purpose":"CLI entry point for managed extraction modules."},
 {"id":"cpp","mode":"static","purpose":"C++ source/native marker evidence; no target execution."},
 {"id":"c","mode":"static","purpose":"C source/native marker evidence; no target execution."},
 {"id":"vector","mode":"static","purpose":"Vector/container terminology and structured numeric evidence."},
 {"id":"base64","mode":"decode","purpose":"Strict standard Base64 decode of selected text/evidence."},
 {"id":"base44","mode":"reference","purpose":"Unsupported until an explicit documented Base44 codec is registered."},
 {"id":"zip","mode":"archive","purpose":"Bounded ZIP inventory and safe workspace extraction."},
 {"id":"rar","mode":"archive","purpose":"Optional RAR inventory through installed backend; no password guessing."},
 {"id":"7zip","mode":"archive","purpose":"Optional 7z inventory through py7zr; no password guessing."},
 {"id":"semgrep","mode":"optional-static","purpose":"Static source-code rules on user-selected source/workspace."},
 {"id":"blob","mode":"static","purpose":"Raw blob size/header/zero-density evidence."},
 {"id":"chunk","mode":"static","purpose":"Bounded byte-range chunk map with exact offsets."},
 {"id":"svg","mode":"static","purpose":"SVG/XML structure inventory."},
 {"id":"xml","mode":"static","purpose":"XML element/root structure inventory."},
 {"id":"css","mode":"static","purpose":"CSS selector/property token inventory."},
 {"id":"formatcode","mode":"static","purpose":"Auto-route known source/text/archive formats to safe extractors."},
 {"id":"wildcard","mode":"static","purpose":"Fallback any-file fingerprint/blob/chunk extraction."},
 {"id":"allcode","mode":"static","purpose":"Normalize all observable code/string evidence."},
 {"id":"codestring","mode":"static","purpose":"ASCII and conservative UTF-16 string extraction with offsets."},
 {"id":"extractormodule","mode":"static","purpose":"Universal file fingerprint, signatures, regions and evidence."},
 {"id":"extractorrefactoring","mode":"analysis","purpose":"Refactor generated extractor/report code, never the imported binary."},
 {"id":"refactoringcode","mode":"analysis","purpose":"Normalize generated reconstruction scaffolds."},
 {"id":"codeencode","mode":"static","purpose":"Encoding evidence and BOM/string classification."},
 {"id":"codeencoder","mode":"export","purpose":"Encode generated reports/JSON/text; imported target remains unchanged."},
 {"id":"library","mode":"reference","purpose":"Built-in semantic symbol and extractor catalog."},
 {"id":"sources","mode":"provenance","purpose":"Record file/hash/offset/encoding provenance for findings."},
 {"id":"ghidra","mode":"optional-static","purpose":"Native PE/ELF static-analysis adapter when Ghidra is installed."},
 {"id":"frida","mode":"optional-runtime","purpose":"Authorized attach-only runtime evidence adapter; no stealth or target modification."},
 {"id":"js","mode":"static","purpose":"JavaScript marker/source evidence."},
 {"id":"vbscript","mode":"static","purpose":"VB/VBScript marker/source evidence."},
 {"id":"scripts","mode":"static","purpose":"Script-language marker inventory."},
 {"id":"toolsextractor","mode":"reference","purpose":"Inventory available managed/system analysis tools."},
]

ALIASES={
 "/workflow":"workflow","/head":"head",
 "/python":"python", "/linux":"linux", "/host":"host", "/pyconverter":"pyconverter", "/pyinverter":"pyinverter", "/pyheader":"pyheader", "/pytrace":"pytrace", "/pylink":"pylink", "/pyurls":"pyurls", "/pydecorder":"pydecorder", "/pyencorder":"pyencorder", "/pylayer":"pylayer", "/pylist":"pylist", "/pyghidra":"pyghidra", "/pyfrida":"pyfrida", "/pynano":"pynano", "/pyupdate":"pyupdate", "/pyupgrade":"pyupgrade",
 "/pypath":"pypath","/pyprocess":"pypath","/pyusage":"pypath","/pyscript":"pypath",
 "/exfallback":"exfallback","/exbots":"exfallback","/autofallback":"exfallback","/exevidence":"exevidence","/giveevidence":"exevidence",
 "/exproblem":"exproblem","/ex4problem":"exproblem","/ex5problem":"exproblem","/exdiagnose":"exproblem","/exaskmt5":"exaskmt5",
 "/mt5ai":"mt5ai","/askmt5":"mt5ai","/mt5mcp":"mt5mcp","/mt5aidiscover":"mt5mcp",
 "/metatrader":"metatrader","/mt4":"metatrader","/mt5":"metatrader","/mtcheck":"mtcheck","/mqlcheck":"mtcheck","/mtcompile":"mtcompile","/mqlcompile":"mtcompile","/help":"help",
 "/mergecode":"mergecode","/combineidea":"combineidea","/codeidea":"codeidea","/codeintelligent":"codeintelligent","/codewrap":"codewrap","/codescriptidea":"codescriptidea",
 "/codecompile":"codecompile","/compilecode":"codecompile","/codeextract":"codeextract","/extractcode":"codeextract","/codeconvert":"codeconvert","/convertcode":"codeconvert",
 "/codeencrypt":"codeencrypt","/codedecrypt":"codedecrypt",
 "/codecheckall":"codecheckall","/codetarget":"codetarget","/codeidentify":"codeidentify","/codemethode":"codemethode","/codemethod":"codemethode",
 "/codeexpanding":"codeexpanding","/codeextra":"codeextra","/codecodecodelayer":"codecodecodelayer","/codelayer":"codecodecodelayer",
 "/skeleton":"skeleton","/troubleshooting":"troubleshooting","/codesummary":"codesummary","/codecheck":"codecheck","/pycheck":"pycheck",
 "/pdfrichhtml":"pdfrichhtml","/pdfocrhtml":"pdfrichhtml","/batchofficehtml":"batchofficehtml","/folder2html":"batchofficehtml",
 "/office2html":"office2html","/document2html":"office2html","/pdf2html":"pdf2html","/word2html":"word2html","/docx2html":"word2html","/excel2html":"excel2html","/xlsx2html":"excel2html","/csv2html":"office2html",
 "/pdfocr":"pdfocr","/ocrpdf":"pdfocr","/ocrscan":"pdfocr","/ocrreadiness":"ocrreadiness","/searchablepdf":"searchablepdf",
 "/officeconvert":"officeconvert","/officeengine":"officeconvert","/officecapabilities":"officecapabilities",
 "/csv2xlsx":"documentconvert","/xlsx2csv":"documentconvert",
 "/documentconvert":"documentconvert","/pdf2word":"pdf2word","/pdf2docx":"pdf2word","/pdf2excel":"pdf2excel","/pdf2xlsx":"pdf2excel",
 "/word2pdf":"word2pdf","/docx2pdf":"word2pdf","/excel2pdf":"excel2pdf","/xlsx2pdf":"excel2pdf","/word2excel":"word2excel","/excel2word":"excel2word",
 "/py":"py","/*.py":"py","/**.***":"anyformat","/convertany":"convertany","/anyformat":"anyformat",
 "/dex2smali":"dex2smali","/smali2dex":"smali2dex","/dex2java":"dex2java","/smali2java":"smali2java","/androidconvert":"androidconvert",
 "/*.dex":"dex","/*.class":"class","/*.jar":"jar","/*.apk":"apk","/*.aab":"aab","/*.wasm":"wasm",
 "/*.db":"sqlite","/*.sqlite":"sqlite","/*.sqlite3":"sqlite","/*.json":"json","/*.pb":"protobuf","/*.protobuf":"protobuf",
 "/*.pak":"pak","/*.img":"img","/*.iso":"iso",
 "/*.exe":"exe","/*.dll":"exe","/*.so":"so","/*.elf":"so","/*.dat":"dat","/*.bin":"dat",
 "/codecli":"codecli","/c++":"cpp","/cpp":"cpp","/c":"c","/vector":"vector",
 "/base64":"base64","/base44":"base44","/zip":"zip","/rar":"rar","/7zip":"7zip",
 "/smgrep":"semgrep","/semgrep":"semgrep","/blob":"blob","/chunk":"chunk",
 "/svg":"svg","/xml":"xml","/css":"css","/*formatcode":"formatcode","/*.**":"wildcard","/*.***":"wildcard",
 "/deep-dive":"extractormodule","/allcode":"allcode","/codestring":"codestring",
 "/extractormodule":"extractormodule","/extractorrefactoring":"extractorrefactoring",
 "/refactoringcode":"refactoringcode","/codeencode":"codeencode","/codeencoder":"codeencoder",
 "/library":"library","/sources":"sources","/ghidra":"ghidra","/frida":"frida",
 "/js":"js","/vbscript":"vbscript","/scripts":"scripts","/toolsextractor":"toolsextractor"
}

def catalog():
    return MODULES

def resolve(command):
    mid=ALIASES.get(command.lower())
    return next((m for m in MODULES if m["id"]==mid),None)
